### ISSUE TITLE
SVG font format proposal

### ISSUE THREAD

**Issue by msurguy** [inconvergent/gridfont#7]
Hello! 

I'm running https://drawingbots.net/ and am building up some browser-based tools that work with SVG fonts that are in the same format as the `svg_fonts` in Hershey Text Inkscape extension by @oskay: https://gitlab.com/oskay/hershey-text/tree/master/hershey-text.

I was wondering if you have considered making the output of this tool into real fonts that could be used in that Inkscape extension or tools that use the same format? 

Thanks!

**Comment by inconvergent** [comment]
Hi

The reason why I made this was that I wanted to create the vectors (as you see in the `paths` property in `dat/*/res.json`. So i haven't really considered making this into SVG fonts. in fact, I wanted to avoid parsing SVG in my own framework.

I would suggest (in the event that people enjoy this font) creating the SVG output in a separate script. could that work? However, seeing as I don't specifically need it, it is not something that i'll be spending time on.

**Comment by inconvergent** [comment]
On second thoughts. I think it should be pretty easy to output the format you point to. And I already create individual SVGs for debugging. if you want to create a PR that does something similar to https://github.com/inconvergent/gridfont/blob/master/gridfont/gridfont.py#L146 (`gridfont.save_svg`) to create the "SVG font", I would certainly be happy to include it here. The only "invasive" change this would require seems to be changing the names of the characters in the `json` definitions.
